/*
 * ambarella_otp_flex_layout.c - CV8 OTP region layout table
 *
 * Copyright (c) 2026 Ambarella International LP
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include "ambarella_otp_flex.h"

#define OTP_CAPS_CUST_RW \
	(OTP_CAP_NW_RD | OTP_CAP_NW_WR | OTP_CAP_SW_RD | OTP_CAP_SW_WR)

#define OTP_CAPS_CUST_RDWR_SW \
	(OTP_CAP_NW_RD | OTP_CAP_SW_RD | OTP_CAP_SW_WR)

#define OTP_CAPS_SW_ONLY \
	(OTP_CAP_SW_RD | OTP_CAP_SW_WR)

#define OTP_REG(_idx, _name, _addr, _size, _hl, _lbank, _lbit, _hi, _ibit, _acl, _caps, _class) \
	[_idx] = { \
		.name = (_name), \
		.index = (_idx), \
		.bit_addr = (_addr), \
		.bit_size = (_size), \
		.has_lock = (_hl), \
		.lock_bank = (_lbank), \
		.lock_bit = (_lbit), \
		.has_invalid_bit = (_hi), \
		.invalid_bit = (_ibit), \
		.acl_bit = (_acl), \
		.caps = (_caps), \
		.region_class = (_class), \
	}

const otp_region_desc_t g_otp_regions[OTP_IDX_REGION_COUNT] = {
	OTP_REG(OTP_IDX_SYS_CONFIG, "sys_config", SYS_CONFIG_BIT_ADDR,
		SYS_CONFIG_BITS, 1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_SYS_CONFIG,
		0, 0, OTP_IDX_SYS_CONFIG, OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),

	OTP_REG(OTP_IDX_UUID, "uuid", UNIQUE_ID_ADDR, UNIQUE_ID_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_UNIQUE_ID,
		0, 0, OTP_ACL_NONE, OTP_CAPS_SW_ONLY, OTP_CLASS_PLAIN),

	OTP_REG(OTP_IDX_WRITE_LOCK, "write_lock", WRITE_LOCK_BIT_ADDR,
		WRITE_LOCK_BITS, 0, 0, 0, 0, 0, OTP_ACL_NONE,
		OTP_CAP_SW_RD, OTP_CLASS_META),

	OTP_REG(OTP_IDX_CST_SEED, "cst_seed", CST_PLANTED_SEED_ADDR,
		CST_PLANTED_SEED_BITS, 1, OTP_LOCK_BANK_WRITE_LOCK,
		LOCK_BIT_CST_PLANTED_SEED_CUK, 0, 0, OTP_IDX_CST_SEED,
		OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),

	OTP_REG(OTP_IDX_CST_CUK, "cst_cuk", CST_PLANTED_CUK_ADDR,
		CST_PLANTED_CUK_BITS, 1, OTP_LOCK_BANK_WRITE_LOCK,
		LOCK_BIT_CST_PLANTED_SEED_CUK, 0, 0, OTP_IDX_CST_CUK,
		OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),

	OTP_REG(OTP_IDX_FUNCTION_DISABLE, "function_disable",
		FUNCTION_DISABLE_ADDR, FUNCTION_DISABLE_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_SYS_CONFIG,
		0, 0, OTP_IDX_FUNCTION_DISABLE, OTP_CAPS_CUST_RW,
		OTP_CLASS_PLAIN),

	OTP_REG(OTP_IDX_WRITE_LOCK_2, "write_lock_2", WRITE_LOCK_2_BIT_ADDR,
		WRITE_LOCK_2_BITS, 0, 0, 0, 0, 0, OTP_ACL_NONE,
		OTP_CAP_SW_RD, OTP_CLASS_META),

	OTP_REG(OTP_IDX_SERIAL_NUMBER, "serial_number", CUSTOMER_ID_ADDR,
		CUSTOMER_ID_BITS, 1, OTP_LOCK_BANK_WRITE_LOCK,
		LOCK_BIT_CUSTOMER_ID, 0, 0, OTP_IDX_SERIAL_NUMBER,
		OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),

	OTP_REG(OTP_IDX_TEST_REGION, "test_region", TEST_REGION_ADDR,
		TEST_REGION_BITS, 1, OTP_LOCK_BANK_WRITE_LOCK,
		LOCK_BIT_TEST_REGION, 0, 0, OTP_IDX_TEST_REGION,
		OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),

	OTP_REG(OTP_IDX_HUK, "huk", HUK_ADDR, HUK_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_HUK_NONCE,
		0, 0, OTP_IDX_HUK, OTP_CAPS_SW_ONLY, OTP_CLASS_PLAIN),

	OTP_REG(OTP_IDX_USER_CUK, "user_cuk", USR_PLANTED_CUK_ADDR,
		USR_PLANTED_CUK_BITS, 1, OTP_LOCK_BANK_WRITE_LOCK,
		LOCK_BIT_USR_PLANTED_CUK, 0, 0, OTP_IDX_USER_CUK,
		OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),

	OTP_REG(OTP_IDX_AES_KEY_0, "aes_key_0",
		AES_KEY_BASE_ADDR + 0 * AES_KEY_BITS, AES_KEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_AES_KEY_BASE + 0,
		0, 0, OTP_IDX_AES_KEY_0, OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),
	OTP_REG(OTP_IDX_AES_KEY_1, "aes_key_1",
		AES_KEY_BASE_ADDR + 1 * AES_KEY_BITS, AES_KEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_AES_KEY_BASE + 1,
		0, 0, OTP_IDX_AES_KEY_1, OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),
	OTP_REG(OTP_IDX_AES_KEY_2, "aes_key_2",
		AES_KEY_BASE_ADDR + 2 * AES_KEY_BITS, AES_KEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_AES_KEY_BASE + 2,
		0, 0, OTP_IDX_AES_KEY_2, OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),
	OTP_REG(OTP_IDX_AES_KEY_3, "aes_key_3",
		AES_KEY_BASE_ADDR + 3 * AES_KEY_BITS, AES_KEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_AES_KEY_BASE + 3,
		0, 0, OTP_IDX_AES_KEY_3, OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),

	OTP_REG(OTP_IDX_ECC_KEY_0, "ecc_key_0",
		ECC_KEY_BASE_ADDR + 0 * ECC_KEY_BITS, ECC_KEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_ECC_KEY_BASE + 0,
		0, 0, OTP_IDX_ECC_KEY_0, OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),
	OTP_REG(OTP_IDX_ECC_KEY_1, "ecc_key_1",
		ECC_KEY_BASE_ADDR + 1 * ECC_KEY_BITS, ECC_KEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_ECC_KEY_BASE + 1,
		0, 0, OTP_IDX_ECC_KEY_1, OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),
	OTP_REG(OTP_IDX_ECC_KEY_2, "ecc_key_2",
		ECC_KEY_BASE_ADDR + 2 * ECC_KEY_BITS, ECC_KEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_ECC_KEY_BASE + 2,
		0, 0, OTP_IDX_ECC_KEY_2, OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),
	OTP_REG(OTP_IDX_ECC_KEY_3, "ecc_key_3",
		ECC_KEY_BASE_ADDR + 3 * ECC_KEY_BITS, ECC_KEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_ECC_KEY_BASE + 3,
		0, 0, OTP_IDX_ECC_KEY_3, OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),

	OTP_REG(OTP_IDX_USER_SLOT_0, "user_slot_0",
		USR_SLOT_G0_ADDR + 0 * USR_SLOT_G0_BITS, USR_SLOT_G0_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_USR_SLOT_G0_BASE + 0,
		0, 0, OTP_IDX_USER_SLOT_0, OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),
	OTP_REG(OTP_IDX_USER_SLOT_1, "user_slot_1",
		USR_SLOT_G0_ADDR + 1 * USR_SLOT_G0_BITS, USR_SLOT_G0_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_USR_SLOT_G0_BASE + 1,
		0, 0, OTP_IDX_USER_SLOT_1, OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),
	OTP_REG(OTP_IDX_USER_SLOT_2, "user_slot_2",
		USR_SLOT_G0_ADDR + 2 * USR_SLOT_G0_BITS, USR_SLOT_G0_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_USR_SLOT_G0_BASE + 2,
		0, 0, OTP_IDX_USER_SLOT_2, OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),
	OTP_REG(OTP_IDX_USER_SLOT_3, "user_slot_3",
		USR_SLOT_G0_ADDR + 3 * USR_SLOT_G0_BITS, USR_SLOT_G0_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_USR_SLOT_G0_BASE + 3,
		0, 0, OTP_IDX_USER_SLOT_3, OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),
	OTP_REG(OTP_IDX_USER_SLOT_4, "user_slot_4",
		USR_SLOT_G0_ADDR + 4 * USR_SLOT_G0_BITS, USR_SLOT_G0_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_USR_SLOT_G0_BASE + 4,
		0, 0, OTP_IDX_USER_SLOT_4, OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),
	OTP_REG(OTP_IDX_USER_SLOT_5, "user_slot_5",
		USR_SLOT_G0_ADDR + 5 * USR_SLOT_G0_BITS, USR_SLOT_G0_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_USR_SLOT_G0_BASE + 5,
		0, 0, OTP_IDX_USER_SLOT_5, OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),

	OTP_REG(OTP_IDX_ROT_KEY_0, "rot_key_0",
		ROT_PUBKEY_ADDR + 0 * ROT_PUBKEY_BITS, ROT_PUBKEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK_2, 0,
		1, 0, OTP_IDX_ROT_KEY_0, \
		(OTP_CAP_NW_RD | OTP_CAP_SW_RD | OTP_CAP_SW_WR), OTP_CLASS_ROT_DIGEST),
	OTP_REG(OTP_IDX_ROT_KEY_1, "rot_key_1",
		ROT_PUBKEY_ADDR + 1 * ROT_PUBKEY_BITS, ROT_PUBKEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK_2, 1,
		1, 1, OTP_IDX_ROT_KEY_1, \
		(OTP_CAP_NW_RD | OTP_CAP_SW_RD | OTP_CAP_SW_WR), OTP_CLASS_ROT_DIGEST),
	OTP_REG(OTP_IDX_ROT_KEY_2, "rot_key_2",
		ROT_PUBKEY_ADDR + 2 * ROT_PUBKEY_BITS, ROT_PUBKEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK_2, 2,
		1, 2, OTP_IDX_ROT_KEY_2, OTP_CAPS_CUST_RDWR_SW, OTP_CLASS_ROT_DIGEST),
	OTP_REG(OTP_IDX_ROT_KEY_3, "rot_key_3",
		ROT_PUBKEY_ADDR + 3 * ROT_PUBKEY_BITS, ROT_PUBKEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK_2, 3,
		1, 3, OTP_IDX_ROT_KEY_3, OTP_CAPS_CUST_RDWR_SW, OTP_CLASS_ROT_DIGEST),
	OTP_REG(OTP_IDX_ROT_KEY_4, "rot_key_4",
		ROT_PUBKEY_ADDR + 4 * ROT_PUBKEY_BITS, ROT_PUBKEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK_2, 4,
		1, 4, OTP_IDX_ROT_KEY_4, OTP_CAPS_CUST_RDWR_SW, OTP_CLASS_ROT_DIGEST),
	OTP_REG(OTP_IDX_ROT_KEY_5, "rot_key_5",
		ROT_PUBKEY_ADDR + 5 * ROT_PUBKEY_BITS, ROT_PUBKEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK_2, 5,
		1, 5, OTP_IDX_ROT_KEY_5, OTP_CAPS_CUST_RDWR_SW, OTP_CLASS_ROT_DIGEST),
	OTP_REG(OTP_IDX_ROT_KEY_6, "rot_key_6",
		ROT_PUBKEY_ADDR + 6 * ROT_PUBKEY_BITS, ROT_PUBKEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK_2, 6,
		1, 6, OTP_IDX_ROT_KEY_6, OTP_CAPS_CUST_RDWR_SW, OTP_CLASS_ROT_DIGEST),
	OTP_REG(OTP_IDX_ROT_KEY_7, "rot_key_7",
		ROT_PUBKEY_ADDR + 7 * ROT_PUBKEY_BITS, ROT_PUBKEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK_2, 7,
		1, 7, OTP_IDX_ROT_KEY_7, OTP_CAPS_CUST_RDWR_SW, OTP_CLASS_ROT_DIGEST),
	OTP_REG(OTP_IDX_ROT_KEY_8, "rot_key_8",
		ROT_PUBKEY_ADDR + 8 * ROT_PUBKEY_BITS, ROT_PUBKEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK_2, 8,
		1, 8, OTP_IDX_ROT_KEY_8, OTP_CAPS_CUST_RDWR_SW, OTP_CLASS_ROT_DIGEST),
	OTP_REG(OTP_IDX_ROT_KEY_9, "rot_key_9",
		ROT_PUBKEY_ADDR + 9 * ROT_PUBKEY_BITS, ROT_PUBKEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK_2, 9,
		1, 9, OTP_IDX_ROT_KEY_9, OTP_CAPS_CUST_RDWR_SW, OTP_CLASS_ROT_DIGEST),
	OTP_REG(OTP_IDX_ROT_KEY_10, "rot_key_10",
		ROT_PUBKEY_ADDR + 10 * ROT_PUBKEY_BITS, ROT_PUBKEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK_2, 10,
		1, 10, OTP_IDX_ROT_KEY_10, OTP_CAPS_CUST_RDWR_SW, OTP_CLASS_ROT_DIGEST),
	OTP_REG(OTP_IDX_ROT_KEY_11, "rot_key_11",
		ROT_PUBKEY_ADDR + 11 * ROT_PUBKEY_BITS, ROT_PUBKEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK_2, 11,
		1, 11, OTP_IDX_ROT_KEY_11, OTP_CAPS_CUST_RDWR_SW, OTP_CLASS_ROT_DIGEST),
	OTP_REG(OTP_IDX_ROT_KEY_12, "rot_key_12",
		ROT_PUBKEY_ADDR + 12 * ROT_PUBKEY_BITS, ROT_PUBKEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK_2, 12,
		1, 12, OTP_IDX_ROT_KEY_12, OTP_CAPS_CUST_RDWR_SW, OTP_CLASS_ROT_DIGEST),
	OTP_REG(OTP_IDX_ROT_KEY_13, "rot_key_13",
		ROT_PUBKEY_ADDR + 13 * ROT_PUBKEY_BITS, ROT_PUBKEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK_2, 13,
		1, 13, OTP_IDX_ROT_KEY_13, OTP_CAPS_CUST_RDWR_SW, OTP_CLASS_ROT_DIGEST),
	OTP_REG(OTP_IDX_ROT_KEY_14, "rot_key_14",
		ROT_PUBKEY_ADDR + 14 * ROT_PUBKEY_BITS, ROT_PUBKEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK_2, 14,
		1, 14, OTP_IDX_ROT_KEY_14, OTP_CAPS_CUST_RDWR_SW, OTP_CLASS_ROT_DIGEST),
	OTP_REG(OTP_IDX_ROT_KEY_15, "rot_key_15",
		ROT_PUBKEY_ADDR + 15 * ROT_PUBKEY_BITS, ROT_PUBKEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK_2, 15,
		1, 15, OTP_IDX_ROT_KEY_15, OTP_CAPS_CUST_RDWR_SW, OTP_CLASS_ROT_DIGEST),
	OTP_REG(OTP_IDX_ROT_KEY_16, "rot_key_16",
		ROT_PUBKEY_ADDR + 16 * ROT_PUBKEY_BITS, ROT_PUBKEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK_2, 16,
		1, 16, OTP_IDX_ROT_KEY_16, OTP_CAPS_CUST_RDWR_SW, OTP_CLASS_ROT_DIGEST),
	OTP_REG(OTP_IDX_ROT_KEY_17, "rot_key_17",
		ROT_PUBKEY_ADDR + 17 * ROT_PUBKEY_BITS, ROT_PUBKEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK_2, 17,
		1, 17, OTP_IDX_ROT_KEY_17, OTP_CAPS_CUST_RDWR_SW, OTP_CLASS_ROT_DIGEST),
	OTP_REG(OTP_IDX_ROT_KEY_18, "rot_key_18",
		ROT_PUBKEY_ADDR + 18 * ROT_PUBKEY_BITS, ROT_PUBKEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK_2, 18,
		1, 18, OTP_IDX_ROT_KEY_18, OTP_CAPS_CUST_RDWR_SW, OTP_CLASS_ROT_DIGEST),
	OTP_REG(OTP_IDX_ROT_KEY_19, "rot_key_19",
		ROT_PUBKEY_ADDR + 19 * ROT_PUBKEY_BITS, ROT_PUBKEY_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK_2, 19,
		1, 19, OTP_IDX_ROT_KEY_19, OTP_CAPS_CUST_RDWR_SW, OTP_CLASS_ROT_DIGEST),

	OTP_REG(OTP_IDX_MONO_CNT_0, "mono_cnt_0", MONO_CNT_0_ADDR,
		MONO_CNT_0_BITS, 0, 0, 0, 0, 0, OTP_IDX_MONO_CNT_0,
		OTP_CAPS_CUST_RW, OTP_CLASS_MONO_CNT),
	OTP_REG(OTP_IDX_MONO_CNT_1, "mono_cnt_1", MONO_CNT_1_ADDR,
		MONO_CNT_1_BITS, 0, 0, 0, 0, 0, OTP_IDX_MONO_CNT_1,
		OTP_CAPS_CUST_RW, OTP_CLASS_MONO_CNT),
	OTP_REG(OTP_IDX_MONO_CNT_2, "mono_cnt_2", MONO_CNT_2_ADDR,
		MONO_CNT_2_BITS, 0, 0, 0, 0, 0, OTP_IDX_MONO_CNT_2,
		OTP_CAPS_CUST_RW, OTP_CLASS_MONO_CNT),

	OTP_REG(OTP_IDX_BST_VERSION_VALID, "bst_version_valid", BST_VER_ADDR,
		BST_VER_BITS, 1, OTP_LOCK_BANK_WRITE_LOCK,
		LOCK_BIT_BST_VERSION_VALID, 0, 0, OTP_IDX_BST_VERSION_VALID,
		OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),

	OTP_REG(OTP_IDX_ANCHORING_KEY_0, "anchoring_key_0",
		ANCHORING_KEY_0_ADDR, ANCHORING_KEY_0_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_ANCHORING_KEY_0,
		0, 0, OTP_IDX_ANCHORING_KEY_0, OTP_CAPS_CUST_RW,
		OTP_CLASS_PLAIN),

	OTP_REG(OTP_IDX_ANCHORING_KEY_1, "anchoring_key_1",
		ANCHORING_KEY_1_ADDR, ANCHORING_KEY_1_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_ANCHORING_KEY_1,
		0, 0, OTP_IDX_ANCHORING_KEY_1, OTP_CAPS_CUST_RW,
		OTP_CLASS_PLAIN),

	OTP_REG(OTP_IDX_ACCESS_CONTROL_BITMASK, "access_control_bitmask",
		ACCESS_CONTROL_BITMASK_ADDR, ACCESS_CONTROL_BITMASK_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_ACCESS_CONTROL_BITMASK,
		0, 0, OTP_ACL_NONE, OTP_CAPS_CUST_RW, OTP_CLASS_PLAIN),

	OTP_REG(OTP_IDX_DATA_INVALID, "data_invalid", DATA_INVALID_BIT_ADDR,
		DATA_INVALID_BITS, 0, 0, 0, 0, 0, OTP_ACL_NONE,
		OTP_CAP_SW_RD, OTP_CLASS_META),

	OTP_REG(OTP_IDX_UDS, "uds", UDS_ADDR, UDS_BITS,
		1, OTP_LOCK_BANK_WRITE_LOCK, LOCK_BIT_UDS,
		0, 0, OTP_IDX_UDS, OTP_CAPS_SW_ONLY, OTP_CLASS_PLAIN),
};

const otp_region_desc_t *otp_region_get(otp_region_idx_t idx)
{
	if (idx >= OTP_IDX_REGION_COUNT) {
		return NULL;
	}

	return &g_otp_regions[idx];
}
